apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: web-develop
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "1"
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/startup-cpu-boost: "true"
    spec:
      serviceAccountName: cloud-run-web@math-p-earth.iam.gserviceaccount.com
      containers:
        - image: ${IMAGE}
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
