name: Build and Push to Artifact Registry

on:
  workflow_call:
    inputs:
      app:
        description: App to build
        required: true
        type: string
      docker-tag:
        description: Tag for the docker image
        required: true
        type: string
      region:
        description: Region to build to
        required: true
        type: string
    outputs:
      image-tag:
        description: Full image tag of result image
        value: ${{ jobs.build-push.outputs.image-tag }}

env:
  IMAGE_NAME: ${{ inputs.region }}-docker.pkg.dev/math-p-earth/math-p-earth/${{ inputs.app }}

jobs:
  build-push:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.tag.outputs.IMAGE_TAG }}

    steps:
      - uses: actions/checkout@v3

      - name: Set image tag
        id: tag
        run: |
          IMAGE_TAG=${{ env.IMAGE_NAME }}:${{ inputs.docker-tag }}
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: projects/198474744222/locations/global/workloadIdentityPools/pool/providers/github
          service_account: github-actions@math-p-earth.iam.gserviceaccount.com
          token_format: access_token

      - name: Login to Artifact Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ inputs.region }}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Build and Push to Artifact Registry
        uses: docker/build-push-action@v3
        with:
          push: true
          file: apps/${{ inputs.app }}/Dockerfile
          context: .
          tags: ${{ steps.tag.outputs.IMAGE_TAG }}
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache,mode=max
