name: Build and Push to GitHub Packages

on:
  workflow_call:
    inputs:
      app:
        description: App to build
        required: true
        type: string
      docker-tag:
        description: Tag for the docker image
        required: true
        type: string
    outputs:
      image-tag:
        description: Full image tag of result image
        value: ${{ jobs.build-push.outputs.image-tag }}

env:
  IMAGE_NAME: ghcr.io/math-p-earth/${{ inputs.app }}

jobs:
  build-push:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.tag.outputs.IMAGE_TAG }}

    steps:
      - uses: actions/checkout@v3

      - name: Set image tag
        id: tag
        run: |
          IMAGE_TAG=${{ env.IMAGE_NAME }}:${{ inputs.docker-tag }}
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          push: true
          file: apps/${{ inputs.app }}/Dockerfile
          context: .
          tags: ${{ steps.tag.outputs.IMAGE_TAG }}
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache,mode=max
