name: Release math-worker Production

on:
  push:
    tags:
      - v*

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v3

      - name: Get tag value
        id: tag
        run: |
          TAG=${GITHUB_REF#refs/*/}
          echo "Working tag: $TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

  build-push:
    needs:
      - prepare
    if: ${{ needs.prepare.outputs.tag }}
    uses: ./.github/workflows/build-and-push-github-packages.yml
    with:
      app: web
      docker-tag: ${{ needs.prepare.outputs.tag }}

  deploy:
    needs:
      - prepare
      - build-push
    uses: ./.github/workflows/deploy-server.yml
    with:
      app: web
      image-tag: ${{ needs.prepare.outputs.tag }}
    secrets:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
